iscouttaskdispatch/site/__init__.py
from flask import Blueprint, render_template

from ..database.db import Team
from .views import overview, spielleitung, team

site = Blueprint("site", __name__, template_folder="templates")


site.register_blueprint(spielleitung.spielleitung_site)
site.register_blueprint(team.teams_site)
site.register_blueprint(overview.overview_site)


@site.after_request
def add_header(response):
    response.headers['Cache-Control'] = 'no-store'
    return response


@site.context_processor
def inject_teams():
    data = {}
    data["teams"] = [t.to_dict() for t in Team.get_all()]
    return data


@site.route("/")
def index():
    return render_template("index.html")

iscouttaskdispatch/site/views/spielleitung/__init__.py
import time
from datetime import datetime

from flask import Blueprint, abort, redirect, render_template, request, url_for

from ....tools import formatDatetime
from .task import tasks_site

spielleitung_site = Blueprint(
    "spielleitung", __name__, url_prefix="/spielleitung")


spielleitung_site.register_blueprint(tasks_site)

# activate back button


@spielleitung_site.context_processor
def inject_back():
    return dict(backact=True)


@spielleitung_site.route("/")
def index():
    return render_template("spielleitung/index.html")

iscouttaskdispatch/site/views/task_views.py
# site/views/task_views.py
from flask import render_template, request, redirect, url_for
from ...database.handel import *
from .tools import formatDatetime
from flask import Blueprint
import time
from datetime import datetime

tasks_site = Blueprint("tasks_site", __name__, template_folder="../templates/task", url_prefix="/tasks")

@tasks_site.route("/")
def showAllTasks():
    current_time = datetime.now().strftime('%H:%M:%S')
    teams = {i['teamID']:i['name'] for i in getAllTeams()}
    tasks = getAllTasks()
    for task in tasks:
        task['description'] = task['description'].replace("\r", "").replace("\n","<br>")
        task['teamName'] = teams[task['teamID']] if task['teamID'] != None else "Kein Team Ausgewählt"
        status = getStatusOfTask(task['taskID'])
        task['status'] = status['name']
        task['statusText'] = status['text']
        task['statustimestamp'] = formatDatetime(status['timestamp'])
    return render_template("task/index.html", tasks=tasks, teams=getAllTeams())


@tasks_site.route("/<int:taskID>/edit")
def editTask(taskID):
    task = getTaskViaID(taskID)
    status = getStatusOfTask(task['taskID'])
    task['status'] = status['name']
    return render_template("task/edit.html", task=task)


@tasks_site.route("/<int:taskID>/update", methods=["POST"])
def updateTask(taskID):
    name = request.form.get("name")
    description = request.form.get("description")
    status = int(request.form.get("new_status"))
    task = getTaskViaID(taskID)
    if task['name'] != name or task['description'] != description or getStatusOfTask(taskID)['statusID'] != status:
        setTaskName(taskID, name)
        setTaskDescription(taskID, description)
        setTaskStatus(taskID, status, "set Status via UI")
    return redirect(url_for("site.tasks_site.showAllTasks"))


@tasks_site.route("/create", methods=["GET", "POST"])
def createTaskSite():
    error_message = None
    form_data = {"taskID": None, "name": "", "description": ""}

    if request.method == "POST":
        form_data["taskID"] = int(request.form.get("taskID"))
        form_data["name"] = request.form.get("name")
        form_data["description"] = request.form.get("description")

        try:
            createTask(form_data["taskID"], form_data["name"], form_data["description"], "Created via UI")
            return redirect(url_for("site.tasks_site.showAllTasks"))
        except ElementAlreadyExists:
            error_message = "Task with the provided ID already exists."
        except Exception as ex:
            error_message = str(ex)

    return render_template("task/create.html", error_message=error_message, form_data=form_data)


@tasks_site.route("/<int:taskID>/delete", methods=["POST"])
def deleteTaskSite(taskID):
    error_message = None
    if request.method == "POST":
        try:
            deleteTask(taskID)
            return redirect(url_for("site.tasks_site.showAllTasks"))
        except ElementDoesNotExsist:
            error_message = "Task with the provided ID does not exists."
            # You can handle the error as needed, such as displaying a message to the user.

    return render_template("error.html", error_message=error_message)


@tasks_site.route("/<int:taskID>/assign", methods=["POST"])
def assignTaskSite(taskID):
    teamID = request.form.get("team", type=int)
    assignTask(taskID, teamID, "Assigned via WEB UI")
    return redirect(url_for("site.tasks_site.showAllTasks"))


@tasks_site.route("/<taskID>")
def specificTask(taskID):
    teams = {i['teamID']:i['name'] for i in getAllTeams()}
    statuses = getAllStatusesOfTask(int(taskID))
    for status in statuses:
        status['timestamp'] = formatDatetime(status['timestamp'])
    task = getTaskViaID(taskID)
    task['description'] = task['description'].replace("\r", "").replace("\n","<br>")
    task['teamName'] = teams[task['teamID']] if task['teamID'] != None else "Kein Team Ausgewählt"
    return render_template("task/task.html", task=task, statuses=statuses)

iscouttaskdispatch/site/templates/spielleitung/tasks/create.html
{% extends 'spielleitung/tasks/index.html' %}

{% block title %}Create Task{% endblock %}

{% block content %}
<div>
    <h1>Create Task</h1>
    <form action="" method="post">
        {{ form.hidden_tag() }}

        <div class="form-floating mb-3">
            {{ form.taskID(class="form-control" + (' is-invalid' if form.taskID.errors else '')) }}
            {{ form.taskID.label }}
            {% if form.taskID.errors %}
            <div class="invalid-feedback">
                {{ form.taskID.errors[0] }}
            </div>
            {% endif %}
        </div>


        <div class="form-floating mb-3">
            {{ form.name(class="form-control") }}
            {{ form.name.label }}
        </div>

        <div class="form-floating mb-3">
            {{ form.description(class="form-control", style="height: 200px") }}
            {{ form.description.label }}
        </div>

        <div class="form-floating mb-3">
            {{ form.format(class="form-control") }}
            {{ form.format.label }}
        </div>

        <div class="form-floating mb-3">
            {{ form.link(class="form-control") }}
            {{ form.link.label }}
        </div>

        <div class="form-floating mb-3">
            {{ form.comment(class="form-control") }}
            {{ form.comment.label }}
        </div>

        {{ form.submit(class="btn btn-primary") }}
    </form>
</div>


<script>
    document.getElementById('description').addEventListener('paste', function (event) {
        // Delay to allow the paste to complete
        setTimeout(() => {
            const text = event.target.value;

            // Regular expression to detect URLs
            const urlRegex = /(https?:\/\/[^\s]+)/g;

            // Find the first match
            const match = text.match(urlRegex);

            if (match) {
                // Extract the first URL
                let url = match[0];

                // Remove trailing dot, whitespace, or newline if present
                url = url.replace(/[\.\s\n\r]+$/, '');

                // Write the sanitized URL to the input
                document.getElementById('link').value = url;
            } else {
                // Clear the input if no URL is found
                document.getElementById('link').value = '';
            }
        }, 0);
    });
</script>

{% endblock %}

iscouttaskdispatch/site/templates/spielleitung/tasks/edit.html
{% extends 'spielleitung/tasks/index.html' %}

{% block title %}Edit Task {{task.id}}{% endblock %}

{% block content %}
<form action="" method="post">
    <div>
        <h1>Edit Task {{task.id}}</h1>

        {{ form.hidden_tag() }}

        <div class="form-floating mb-3">
            {{ form.name(class="form-control") }}
            {{ form.name.label }}
        </div>

        <div class="form-floating mb-3">
            {{ form.description(class="form-control", style="height: 200px") }}
            {{ form.description.label }}
        </div>

        <div class="form-floating mb-3">
            {{ form.format(class="form-control") }}
            {{ form.format.label }}
        </div>

        <div class="form-floating mb-3">
            {{ form.link(class="form-control") }}
            {{ form.link.label }}
        </div>

        <div class="form-floating mb-3">
            {{ form.comment(class="form-control") }}
            {{ form.comment.label }}
        </div>

        <div class="form-floating mb-3">
            {{ form.team(class="form-select") }}
            {{ form.team.label }}
        </div>

        <div class="accordion mb-3">
            <div class="accordion-item">
                <h2 class="accordion-header">
                    <button class="accordion-button collapsed" type="button" data-bs-toggle="collapse"
                        data-bs-target="#panelsStayOpen-collapseTwo" aria-expanded="false"
                        aria-controls="panelsStayOpen-collapseTwo">
                        <span class="text-danger"> Danger Zone </span>
                    </button>
                </h2>
                <div id="panelsStayOpen-collapseTwo" class="accordion-collapse collapse">
                    <div class="accordion-body">
                        <div class="form-floating mb-3">
                            {{ form.status(class="form-select") }}
                            {{ form.status.label }}
                        </div>

                        <button type="button" class="btn btn-danger" data-bs-toggle="modal"
                            data-bs-target="#deleteModal">
                            Task Löschen
                        </button>
                    </div>
                </div>
            </div>
        </div>



        <div>
            <a href="{{back}}" class="btn btn-secondary"> Abbrechen </a>

            {{ form.submit(class="btn btn-primary") }}
        </div>

        <hr class="mt-5">
        <div class="accordion" id="accordionExample">
            <div class="accordion-item">
                <h2 class="accordion-header">
                    <button class="accordion-button" type="button" data-bs-toggle="collapse"
                        data-bs-target="#collapseOne" aria-expanded="true" aria-controls="collapseOne">
                        Logs
                    </button>
                </h2>
                <div id="collapseOne" class="accordion-collapse collapse show" data-bs-parent="#accordionExample">
                    <div class="accordion-body">
                        {% for log in logs %}
                        {{ log }} <br>
                        {% endfor %}
                    </div>
                </div>
            </div>
        </div>
    </div>


    <div class="modal fade" id="deleteModal" tabindex="-1" aria-labelledby="deleteModalLabel" aria-hidden="true">
        <div class="modal-dialog">
            <div class="modal-content">
                <div class="modal-header">
                    <h1 class="modal-title fs-5" id="deleteModalLabel">Löschen</h1>
                    <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                </div>
                <div class="modal-body">
                    Bist du Sicher das du diese Aufgabe löschen möchtest?
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
                    {{ form.delete(class="btn btn-danger") }}
                </div>
            </div>
        </div>
    </div>
</form>
{% endblock %}

iscouttaskdispatch/site/templates/spielleitung/tasks/index.html
{% extends 'spielleitung/index.html' %}

{% block title %}Task List{% endblock %}


{% block content %}
<div>
    <h1>Tasks</h1>
    <a class="btn btn-primary" href="{{ url_for('.create') }}">Create New</a>
    <table class="table table-hover">
        <thead>
            <tr>
                <th>Task ID</th>
                <th>Name</th>
                <th>Description</th>
                <th>Team</th>
                <th>Status</th>
                <!-- <th>Actions</th> -->
            </tr>
        </thead>
        <tbody>
            {% for task in tasks %}
            <tr class="position-relative">
                <td>
                    {{ task.id }}
                    <a href="{{ url_for('site.spielleitung.tasks.show', id=task.id)}}" class="stretched-link"></a>
                </td>
                <td>
                    {{ task.name }}
                </td>
                <td>
                    {{ task.description }}
                </td>
                <td>
                    {% if task.team %}
                    {{ task.team.name }}
                    {% else %}
                    Kein Team zugewiesen
                    {% endif %}
                </td>
                <td>
                    <div class="text-{{ task.status.html_color }}">
                        {{ task.status.name }}
                    </div>
                </td>

                <!-- <td>
                    <a class="btn btn-danger" style="position: relative; z-index: 10;"
                        href="{{ url_for('site.index')}}">
                        <i class="bi bi-exclamation-circle"></i>
                    </a>
                    <a class="btn btn-warning" style="position: relative; z-index: 10;"
                        href="{{ url_for('site.spielleitung.tasks.edit', id=task.id)}}">
                        <i class="bi bi-pencil-fill"></i>
                    </a>
                    <a class="btn btn-outline-success" style="position: relative; z-index: 10;"
                        href="{{ url_for('site.spielleitung.tasks.edit', id=task.id)}}">
                        <i class="bi bi-pencil-fill"></i>
                    </a>
                </td> -->

            </tr>
            {% endfor %}
        </tbody>
    </table>
</div>
{% endblock %}

iscouttaskdispatch/site/templates/spielleitung/tasks/show.html
{% extends 'spielleitung/tasks/index.html' %}

{% block title %}Show Task {{task.id}}{% endblock %}

{% block content %}
<form action="" method="post">
    {{ form.hidden_tag() }}
    <div>
        <div class="card shadow border-0">
            <div class="card-header bg-{{ task.status.html_color }} text-white">
                <div class="d-flex justify-content-between">
                    <div>
                        <h1 class="h4 mb-0">{{ task.id }}. {{ task.name }}</h1>
                    </div>
                    <div>
                        <span class="badge bg-{{ task.status.html_color }} text-white">{{ task.status.name }}</span>
                    </div>
                </div>
            </div>
            <div class="card-body">
                <div class="row mb-3">
                    <div class="col-md-6">
                        <h5 class="fw-bold">Description:</h5>
                        <p>{{ task.description }}</p>
                    </div>
                    <div class="col-md-6">
                        <h5 class="fw-bold">Team:</h5>
                        {% if task.team %}
                        <span class="badge bg-info text-black">{{ task.team.name }}</span>
                        {% else %}
                        <p>Kein Team</p>
                        {% endif %}
                    </div>
                </div>

                <div class="row mb-3">
                    <div class="col-md-6">
                        <h5 class="fw-bold">Format:</h5>
                        <p>{{ task.format }}</p>
                    </div>
                    <div class="col-md-6">
                        <h5 class="fw-bold">Comments:</h5>
                        <p>{{ task.comment if task.comment else 'none' }}</p>
                    </div>
                </div>

                <div class="row mb-3">
                    <div class="col-md-6">
                        <h5 class="fw-bold">Link:</h5>
                        <p>
                            {% if task.link %}
                            <a href="{{ task.link }}" target="_blank">{{ task.link }}</a>
                            {% else %}
                            No link provided
                            {% endif %}

                        </p>
                    </div>

                    <div class="col-md-6">
                        <h5 class="fw-bold">Actions:</h5>

                        <button type="button" class="btn btn-outline-danger" data-bs-toggle="modal"
                            data-bs-target="#failModal">
                            <i class="bi bi-exclamation-circle"></i>
                        </button>

                        <a class="btn btn-outline-warning"
                            href="{{ url_for('site.spielleitung.tasks.edit', id=task.id)}}">
                            <i class="bi bi-pencil"></i>
                        </a>

                        <!-- <button type="submit" name="{{ form.success.name }}" class="btn btn-outline-success"
                            id="{{ form.success.id }}" value="Success">
                            <i class="bi bi-check2"></i>
                        </button> -->

                        <button type="button" class="btn btn-outline-success" data-bs-toggle="modal"
                            data-bs-target="#successModal">
                            <i class="bi bi-check2"></i>
                        </button>
                    </div>
                </div>
            </div>
        </div>

        <hr class="mt-5">

        <div class="accordion" id="taskLogsAccordion">
            <div class="accordion-item">
                <h2 class="accordion-header" id="logsHeading">
                    <button class="accordion-button" type="button" data-bs-toggle="collapse"
                        data-bs-target="#logsCollapse" aria-expanded="true" aria-controls="logsCollapse">
                        Logs
                    </button>
                </h2>
                <div id="logsCollapse" class="accordion-collapse collapse show" aria-labelledby="logsHeading"
                    data-bs-parent="#taskLogsAccordion">
                    <div class="accordion-body">
                        {% for log in task.log.split('\n') %}
                        <div class="log-entry">
                            <p class="mb-1">{{ log }}</p>
                        </div>
                        {% endfor %}
                    </div>
                </div>
            </div>
        </div>
    </div>

    <div class="modal fade" id="failModal" tabindex="-1" aria-labelledby="failModalLabel" aria-hidden="true">
        <div class="modal-dialog">
            <div class="modal-content">
                <div class="modal-header">
                    <h1 class="modal-title fs-5" id="failModalLabel">Fehlgeschlagen?</h1>
                    <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                </div>
                <div class="modal-body">
                    <p>
                        Bist du Sicher das du diese Aufgabe als <span class="badge text-bg-danger">Fehlgeschlagen</span>
                        Markieren möchtest?
                    </p>

                    <div class="form-floating">
                        {{ form.comment(class="form-control") }}
                        {{ form.comment.label }}
                    </div>
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Abbrechen</button>
                    {{ form.failed(class="btn btn-danger", value="Fehlgeschlagen") }}
                </div>
            </div>
        </div>
    </div>

    <div class="modal fade" id="successModal" tabindex="-1" aria-labelledby="successModalLabel" aria-hidden="true">
        <div class="modal-dialog">
            <div class="modal-content">
                <div class="modal-header">
                    <h1 class="modal-title fs-5" id="successModalLabel">Fertig?</h1>
                    <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                </div>
                <div class="modal-body">
                    <p>
                        Bist du Sicher das du diese Aufgabe als <span class="badge text-bg-success">Fertig</span>
                        markieren
                        möchtest?
                    </p>
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Abbrechen</button>
                    {{ form.success(class="btn btn-success", value="Fertig") }}
                </div>
            </div>
        </div>
    </div>
</form>

{% endblock %}